### ISSUE TITLE
Support for Transparency

### ISSUE THREAD

**Issue by ItsMeAshiq** [dataflowg/g-image#6]
Currently the **Save Animated GIF Image.vi** is writing all the frames replacing the Transparent background with white solid color.
![image](https://user-images.githubusercontent.com/87473267/201508827-053fe05f-89dd-40d4-831c-d0ba65633f3e.png)

I believe it is coming straightly from the [**gif.h**](https://github.com/dataflowg/g-image/blob/b45a76938f2ea86a9653382eec9adf4d7622e227/src/C++/gif.h) library implementation.

I think we can do something about it to bring the Transparency support,
![image](https://user-images.githubusercontent.com/87473267/201509773-d47ba91d-f76e-4c71-b436-90b6cd19acce.png)

**Comment by dataflowg** [comment]
Thanks for the suggestion @ItsMeAshiq. I think a gif file indicates whether it has transparency or not, and what color in the palette to use as the transparent color. So there might need to be some extra logic to convert a LabVIEW picture with 256 colors + mask to a 255 color + transparent color. There might also need to be a tweak to the frame disposal method of the animated gif. Definitely a feature that should be supported though :+1:

**Comment by dataflowg** [comment]
Added in [v0.5.0](https://github.com/dataflowg/g-image/releases/tag/v0.5.0). Transparency is applied using either the alpha channel in a 32-bit image, or from the mask in a 8-bit or 24-bit image.
